name: hello_fultter
description: A new Flutter project.

# 以下内容定义了您的应用程序的版本和内部版本号。
# 版本号是由点分隔的三个数字，例如1.2.43
# 后跟一个可选的内部版本号，并用+隔开。
# 版本和构建器编号都可能会被覆盖
# 通过分别指定--build-name和--build-number进行构建。
# 在Android中，内部版本名称用作versionName，而内部版本编号用作versionCode。
# 在以下位置了解有关Android版本的更多信息。
# 在https://developer.android.com/studio/publish/versioning
# 在iOS中，内部版本名称用作CFBundleShortVersionString，而内部版本编号用作CFBundleVersion。
# 在以下位置了解有关iOS版本控制的更多信息
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # 以下内容将Cupertino Icons字体添加到您的应用程序。
  # 与CupertinoIcons类一起用于iOS样式图标。
  cupertino_icons: ^0.1.2
  # 新添加远程的依赖 （也可依赖git仓库中的包，及本地包）
  english_words: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter


# 有关此文件的通用Dart部分的信息，请参见
# 下一页：https://dart.dev/tools/pub/pubspec

# 以下部分专门针对Flutter。
flutter:

  # 下一行确保您的应用程序中包含了Material Icons字体，以便您可以使用material Icons类中的图标。
  uses-material-design: true

  # 要将资产添加到您的应用程序，请添加资产部分，如下所示：
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # 图片资产可以引用一个或多个分辨率特定的“变量”，请参见
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # 有关从包依赖项添加资产的详细信息，请参见
  # https://flutter.dev/assets-and-images/#from-packages

  # 要将自定义字体添加到您的应用程序中，请在此处添加字体部分，
  # 在“flutter”部分中。 此列表中的每个条目都应有一个
  # 带有字体系列名称的“ family”键和带有字体的列表的“ fonts”键给出了字体的资产和其他描述符。 
  # 例如:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # 有关与软件包相关的字体的详细信息，
  # see https://flutter.dev/custom-fonts/#from-packages
